# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30aaf6c65d9480bdd1ccb769f27a03d47a5dcf9627cdbec2bb781c17f17e247ace7404b9cf215fd2d703bf46952643e2941c94efd288e6663ffdb41e4d2602cf

test:
  secret_key_base: 2186e353771e6c9f04f5f7b360588ed45f98202344ca27f746c1cacd14253c12859cbc4008af586ac2e6600ed25d3c563f17aa52dcfd710d3007dd7404baf599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
